'use client'

import { AppContextProvider } from "@/contexts/AppContext";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import type { Metadata } from "next";
import * as React from 'react';
import theme from "./theme/theme";
import AppLayout from "@/components/AppLayout";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {

  return (
    <html lang="ja">
      <body>
        <AppRouterCacheProvider>
          <AppContextProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <AppLayout>{children}</AppLayout>
            </ThemeProvider>
          </AppContextProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
